# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
#dist: trusty
#sudo: required
os:
  - osx
  - linux
julia:
  - 0.5
  - 0.6
  - nightly
env:
    - PYTHON=""
notifications:
  email: false
script:
    - julia -e 'Pkg.clone(pwd())'
    - julia -e 'Pkg.build("TensorFlow")'
    - julia -e 'Pkg.test("TensorFlow", coverage=true)'
after_success:
- julia -e 'cd(Pkg.dir("TensorFlow")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
- julia -e 'Pkg.add("Documenter")'
- julia -e 'cd(Pkg.dir("TensorFlow")); include(joinpath("docs", "make.jl"))'
matrix:
  allow_failures:
    - julia: nightly
